
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Returns whether a database is currently open in memory.
 */
async isDbOpen() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_db_open") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Closes the currently open database (if any).
 */
async closeDb() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_db") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads a database from disk and keeps it open in memory.
 * 
 * Note: The frontend should NOT expect the database file contents to be returned.
 * Instead, subsequent commands should operate against the in-memory database.
 */
async loadDb({ path, masterPassword }: { path: string; masterPassword: string }) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_db", { path, masterPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves the currently open database to disk using the provided master password.
 * 
 * - `atomic = true` writes to a temporary file and then renames it into place.
 * - `atomic = false` writes directly to the destination file path.
 */
async saveDb({ path, masterPassword, atomic }: { path: string; masterPassword: string; atomic: boolean }) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_db", { path, masterPassword, atomic }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists entries from the open database.
 */
async listEntries() : Promise<Result<EntryDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_entries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds an entry to the in-memory database.
 */
async addEntry({ icon, username, password, url, expiryUnix, expiryOffsetSecs, notes }: { icon: string; username: string; password: string; url: string; expiryUnix: number | null; expiryOffsetSecs: number | null; notes: string }) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_entry", { icon, username, password, url, expiryUnix, expiryOffsetSecs, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new database and loads it into memory.
 */
async newDb({ encryption, compression, kdfVariant, kdfIterations, kdfMemoryKb, kdfThreads }: { encryption: number | null; compression: number | null; kdfVariant: number | null; kdfIterations: number; kdfMemoryKb: number; kdfThreads: number }) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_db", { encryption, compression, kdfVariant, kdfIterations, kdfMemoryKb, kdfThreads }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type EntryDto = { icon: string; username: string; url: string; expiry_unix: number | null; expiry_offset_secs: number | null; notes: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
